### PR TITLE
Use an image from sbtscala/scala-sbt

### PR DESCRIPTION
**Pull request by artamonovkirill**
- recommended base image
- scala 2.13 already installed
- current Java LTS release
- has ARM version

### CODE REVIEW

**Comment by artamonovkirill** [comment]
Takes around 10 seconds to run locally:
```
⋊> ~/w/e/s/scala-test-runner on chore/scala-sbt-image ◦ time ./bin/run-in-docker.sh two-fer /Users/kirill/workspace/exercism/scala/two-fer /Users/kirill/workspace/exercism/scala/two-fer
[+] Building 0.7s (12/12) FINISHED                                                                                                      
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 37B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 34B                                                                                                   0.0s
 => [internal] load metadata for docker.io/sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.2_2.13.10                                 0.5s
 => [internal] load build context                                                                                                  0.0s
 => => transferring context: 26.56kB                                                                                               0.0s
 => [1/7] FROM docker.io/sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.2_2.13.10@sha256:94fab089ef539edd8331865d2255a5af71de0a520  0.0s
 => CACHED [2/7] WORKDIR /opt/test-runner                                                                                          0.0s
 => CACHED [3/7] COPY project/ project/                                                                                            0.0s
 => CACHED [4/7] COPY src/ src/                                                                                                    0.0s
 => CACHED [5/7] COPY build.sbt build.sbt                                                                                          0.0s
 => CACHED [6/7] RUN sbt assembly                                                                                                  0.0s
 => CACHED [7/7] COPY . .                                                                                                          0.0s
 => exporting to image                                                                                                             0.0s
 => => exporting layers                                                                                                            0.0s
 => => writing image sha256:e1fdf9cf5ddcecd7ac0b8fe5e43d8ec273b8fc389dac7f3a8bd9f1f7db6d5460                                       0.0s
 => => naming to docker.io/exercism/test-runner                                                                                    0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

two-fer: testing...
two-fer: done

________________________________________________________
Executed in    8.87 secs      fish           external
   usr time  198.23 millis    0.07 millis  198.16 millis
   sys time  260.57 millis    1.06 millis  259.52 millis
```

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
It says "done", but no `results.json` file is being written. Check the output directory for a `results.json` file, which is what the test runner should create. Instead, there is a `runner.log` containing:

```shell
Exception in thread "main" java.io.FileNotFoundException: /tmp/exercise/test-reports/TEST-TwoFerTest.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at scala.io.Source$.fromFile(Source.scala:57)
	at Application$.getTestSuiteObject(Application.scala:24)
	at Application$.toExercismJSON(Application.scala:60)
	at Application$.writeResultsJSON(Application.scala:18)
	at Application$.delayedEndpoint$Application$1(Application.scala:12)
	at Application$delayedInit$body.apply(Application.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Application$.main(Application.scala:6)
	at Application.main(Application.scala)
```

**Comment by artamonovkirill** [comment]
Found it: the file name is `TEST-TwoferTest.xml`, not `TEST-TwoFerTest.xml`

**Comment by ErikSchierboom** [comment]
@artamonovkirill That's coming from https://github.com/exercism/scala-test-runner/blob/main/bin/run.sh#L28. And that is what I meant with the mismatch of filenames in the issue where we discussed this.

**Review by ErikSchierboom — APPROVED** [review]
Let's get this merged and then you can properly test https://github.com/exercism/scala-test-runner/pull/38

**Pull request merged**
