### PR TITLE
Fix running tests with numeric names

### PR DESCRIPTION
**Pull request by artamonovkirill**
E.g., Grains

### CODE REVIEW

**Comment by iHiD** [comment]
Thanks! (cc @ErikSchierboom)

**Review by ErikSchierboom — APPROVED** [review]
Lovely! Thanks

**Comment by ErikSchierboom** [comment]
Is this ready for review?

**Comment by artamonovkirill** [comment]
> Is this ready for review?

From my side - yes. Not sure if @iHiD wanted to add anything

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
LGTM! Thanks for fixing this

**Pull request merged**
