### PR TITLE
Add support for exercises with Lenses

### PR DESCRIPTION
**Pull request by jcranky**
This enables compiling exercises and running tests with Monocle Lens.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by jcranky** [comment]
@ErikSchierboom I was also thinking that it might be worth re-writing the exercise's description, to make it a bit less generic. Wdyt? If you think it makes sense, I could send a proposal in a PR :)

**Comment by ErikSchierboom** [comment]
@jcranky The exercise description itself is "fixed," as it comes from a shared source: https://github.com/exercism/problem-specifications/blob/main/exercises/lens-person/description.md That source though should actually be made _more_ generic, as it now contains an explicit reference to Haskell (which it shouldn't).

We do have a mechanism to allow additional text to be added to an exercise's instructions, via a `instructions.append.md` file. See [the docs](https://exercism.org/docs/building/tracks/practice-exercises#h-file-docs-instructions-append-md) for more information.

What I think need to be is:

1. Update the shared description in the problem-specifications repo to not be specific to Haskell.
2. Add the `instructions.append.md` file to the `lens-person` exercise's `.docs` folder to allow for Scala-specific additions.

PRs would be much appreciated, thanks!

**Comment by jcranky** [comment]
Ah, I didn't know it works like that, that's interesting.
I'll take a shot at creating a couple of PRs for that :)

**Comment by jcranky** [comment]
@ErikSchierboom just to be sure I understand what is going on.

This file: https://github.com/exercism/scala/blob/main/exercises/practice/lens-person/.docs/instructions.md

Has basically the same contents as https://github.com/exercism/problem-specifications/blob/main/exercises/lens-person/description.md - how did that end up there? Is the first one somehow automatically created based on the second?

**Comment by ErikSchierboom** [comment]
Yep. We have a tool called `configlet` (see [the docs](https://exercism.org/docs/building/configlet)) that is used to sync the contents.

**Comment by jcranky** [comment]
PRs created:
- https://github.com/exercism/problem-specifications/pull/2092
- https://github.com/exercism/scala/pull/732

**Pull request merged**
